site_name: Semigroups - Zero to ε

nav:
  - Home: index.md
  - Semigroups in GAP:
      - gap/index.md
      - "GAP: Installation": gap/install.md
      - "GAP: First steps": gap/session.md
      - "GAP: Finite, f.g. and acting semigroups": gap/worksheet1.md
      - "GAP: Finitely presented semigroups": gap/fp.md
  - Semigroups in Python:
      - py/index.md
      - "Python: Installation": py/install.md
      - "Python: First steps": py/first-steps.md
      - "Python: Finite and f.g. semigroups": py/finite.md
      - "Python: Finitely presented semigroups": py/fp.md
  - minizinc:
      - minizinc/index.md

theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips

plugins:
  # - optimize
  # - privacy
  - search

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

copyright: Copyright &copy; 2026 James Mitchell, Reinis Cirpons and Joe Edwards

extra:
  social:
    - name: The Semigroups package
      icon: fontawesome/brands/github
      link: https://www.github.com/semigroups/Semigroups
    - name: The libsemigroups_pybind11 project
      icon: fontawesome/brands/github
      link: https://www.github.com/libsemigroups/libsemigroups_pybind11

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
