site_name: Semigroups - Zero to ε

nav:
  - Home: index.md
  - Semigroups in GAP:
      - gap/index.md
      - "GAP: Installation": gap/install.md
      - "GAP: First steps": gap/first-steps.md
      - "GAP: Semigroups defined by generators": gap/generated.md
      - "GAP: Finitely presented semigroups": gap/fp.md
      - "GAP: Worksheet": gap/worksheet.md
  - Semigroups in Python:
      - py/index.md
      - "Python: Installation": py/install.md
      - "Python: First steps": py/first-steps.md
      - "Python: Semigroups defined by generators": py/generated.md
      - "Python: Finitely presented semigroups": py/fp.md
      - "Python: Worksheet": py/worksheet.md
  - Examples:
      - examples/index.md
      - examples/short.md
      - "Verifying presentations in the ATLAS of Finite Groups":
          - examples/atlas/index.md
          - "Mathieu groups":
              - examples/atlas/mathieu/m11.md
              - examples/atlas/mathieu/m12.md
              - examples/atlas/mathieu/m22.md
              - "Mathieu group M23":
                  - examples/atlas/mathieu/m23/index.md
              - "Mathieu group M24":
                  - examples/atlas/mathieu/m24/index.md
          - "Leech lattice groups":
              - examples/atlas/leech-lattice/hs.md
              - examples/atlas/leech-lattice/j2.md
              - "Conway group Co2":
                  - examples/atlas/leech-lattice/co2/index.md
              - "McLaughlin group McL":
                  - examples/atlas/leech-lattice/mcl/index.md
          - "Monster sections":
              - "Held group He":
                  - examples/atlas/monster-sections/he/index.md
              - "Fischer group Fi22":
                  - examples/atlas/monster-sections/fi22/index.md
          - "Pariahs":
              - examples/atlas/pariahs/j1.md
              - examples/atlas/pariahs/j3.md
              - "Rudvalis group Ru":
                  - examples/atlas/pariahs/ru/index.md
              - "Janko group J4":
                  - examples/atlas/pariahs/j4/index.md
          - "Miscellaneous":
              - examples/atlas/misc/t.md

theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips

plugins:
  # - optimize
  # - privacy
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde

copyright: Copyright &copy; 2026 Reinis Cirpons, Joe Edwards and James Mitchell

extra:
  social:
    - name: The Semigroups package
      icon: fontawesome/brands/github
      link: https://www.github.com/semigroups/Semigroups
    - name: The libsemigroups_pybind11 project
      icon: fontawesome/brands/github
      link: https://www.github.com/libsemigroups/libsemigroups_pybind11

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
