name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  doc-warnings:
    name: Check doc builds without warnings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build in strict mode
        # The strict flag treats warnings as errors
        run:
          pipx run --with mkdocs-material --with mkdocs-awesome-nav mkdocs build
          --clean --strict

# TODO: test the code snippets
